### ISSUE TITLE
No matching Aura/Di package found

### ISSUE THREAD

**Issue by galactic-void** [radarphp/Radar.Project#10]
The latest update to composer has missing packages

```
  Problem 1
    - radar/adr 1.0.0-alpha3 requires aura/di ~3.0.0@alpha -> no matching package found.
    - radar/adr 1.0.0-alpha2 requires aura/di ~3.0 -> no matching package found.
    - radar/adr 1.0.0-alpha1 requires aura/di ~3.0 -> no matching package found.
    - Installation request for radar/adr ~1.0.0@alpha -> satisfiable by radar/adr[1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-alpha3].
```

**Comment by pmjones** [comment]
@harikt Hey man -- did your changes break something?

@galactic-void -- checking into it now, thanks!

**Comment by pmjones** [comment]
@galactic-void: i just pushed changes to Radar.Adr and Radar.Project -- try updating them both and let me know. Sorry for the hassle.

**Comment by galactic-void** [comment]
Working again, Thanks.

**Comment by pmjones** [comment]
Good deal. Again, my apologies for the break.

**Comment by harikt** [comment]
Hi @galactic-void , @pmjones 

Sorry for being late here, I have some trouble with connectivity :-) . About the use case what you could do was add `"minimum-stability":"alpha"` to the `composer.json` of root of project. But I know that will not fix the issue for Aura.Payload was not released to make use of the https://github.com/auraphp/Aura.Payload/pull/2 . So the alpha version still depends on dev. 

So the fastest fix is add `"minimum-stability": "dev"` to the root `composer.json` of your project which will download all the dev versions of the dependencies.

I am sending a PR https://github.com/radarphp/Radar.Project/pull/11 , but as noted above the dependencies need to get fixed.

Thank you.
