### ISSUE TITLE
HTTP 500 and odd output

### ISSUE THREAD

**Issue by cxj** [radarphp/Radar.Project#17]
If one misdefines the __construct() signature for a Domain class, such that the number of arguments it receives is different from what is passed, two things happen:
1. The HTTP status is set to 500 Server Error.
2. The output contains the string "MyClassName::$input" where MyClassName is the name I passed as the domain string, the rest inside the quote marks is literal.  I have no idea where the heck this is coming from, but it's showing up on standard output -- that is, I get a blank web page with only that text on it.

The former (500) is somewhat understandable, but the latter is truly confusing.  Ideally, I'd like to see better documentation on the Domain API, so that it's more obvious what one's constructor should expect.  

And even more ideally, if the code could somehow determine the arguments mismatched and report that in some fashion, it'd be nice.  Maybe provide an injectable error reporting mechanism, e.g. a callable, so plebes like me could dump it to an error log or something.

**Comment by pmjones** [comment]
You're right, that's a sucky behavior. My days are filled right now, so if you want to track it down and put notes on this issue, that will help a lot. If you have the time and inclination to send a PR that would be fantastic but I know you're busy too.

**Comment by cxj** [comment]
It appears the stdout output is coming from file `relay/middleware/src/ExceptionHandler.php`.  This function is writing it to the response body.  Question is where is the exception getting thrown?  Will see if I can find it.

``` php
    public function __invoke(Request $request, Response $response, callable $next)
    {
        try {
            $response = $next($request, $response);
        } catch (Exception $e) {
            $response = $this->exceptionResponse->withStatus(500);
            $response->getBody()->write($e->getMessage());
        }
        return $response;
    }
```

**Comment by cxj** [comment]
Shouldn't `$next` be a string containing the name of the function/method to call in the `try` clause?  It appears to be an object with circular references, which is making it hard to debug.

**Comment by pmjones** [comment]
`$next` is the callable to the "next" middleware; it's actually the Runner, which shifts the next middleware off the queue.

**Comment by cxj** [comment]
`gettype($next)` returns "object" so maybe something is getting corrupted upstream.

**Comment by pmjones** [comment]
Try get_class($next).

**Comment by cxj** [comment]
`get_class($next)` returns "Relay\Relay".

**Comment by cxj** [comment]
Stack trace.

```
#0 relay/relay/src/Relay.php(75): Relay\Middleware\ExceptionHandler->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Relay\Relay))
#1 relay/middleware/src/ResponseSender.php(11): Relay\Relay->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#2 relay/relay/src/Relay.php(75): Relay\Middleware\ResponseSender->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Relay\Relay))
#3 radar/adr/src/Adr.php(45): Relay\Relay->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#4 /radar/web/index.php(100): Radar\Adr\Adr->run(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 {main}
```

**Comment by cxj** [comment]
Looks like it's being thrown from `vendor/aura/di/src/Resolver/Resolver.php` line 239 in my installation, which is here:

``` php
    protected function mergeParamsEmpty($class, &$params)
    {
        foreach ($params as $key => $val) {
            // is the param missing?
            if ($val instanceof UnresolvedParam) {
                throw new Exception\MissingParam($val->getName($class));
            }
            // load lazy objects as we go
            if ($val instanceof LazyInterface) {
                $params[$key] = $val();
            }
        }
    }
```

Don't know why I didn't use the handle Exception methods to get here sooner.  :-p

**Comment by cxj** [comment]
Hmm, this presents a somewhat ugly problem, if I'm understanding everything correctly.  PHP has no way to differentiate types of exceptions (e.g. the difference between Exception\LogicException and Exception\RuntimeException) other than to examine the object via one of several methods.

In the middleware ExceptionHandler class, one could do something like this:

``` php
if ($e instanceof Exception\LogicException) { }
else if ($e instanceof Exception\RuntimeException) { }
else if ($e instanceof Exception\MissingParam) { }
// etc.
```

But that seems really ugly.

If Exception had a Type string, one could use a `switch` statement instead, e.g. `switch($e->getType())` although that's only a little better.

The problem with catching thrown exceptions in general is at least partly one of defining and documenting yet another entire API in a sense.  The DI code is throwing a bunch of exceptions.  The Relay middleware knows enough to `try/catch` but it doesn't _know_ all the exceptions well enough to format a clear message to the user or developer.

Alternatively, all of the `throw new Exception...` statements in Aura, Relay, etc. could (should?) include clear message text, even though that makes the API sort of non-computer interpretable.  As much as it galls me to say this, that's what Zend does, and it might well be the right solution.  For example, the above DI method might look like this, instead:

``` php
protected function mergeParamsEmpty($class, &$params)
{
    foreach ($params as $key => $val) {
        // is the param missing?
        if ($val instanceof UnresolvedParam) {
            throw new Exception\MissingParam("missing param in class: " . $val->getName($class));
        }
        // load lazy objects as we go
        if ($val instanceof LazyInterface) {
            $params[$key] = $val();
        }
    }
}
```

**Comment by cxj** [comment]
It might then also make sense to re-code Relay's `ExceptionHandler` a bit to look like this:

``` php
public function __invoke(Request $request, Response $response, callable $next)  {
    try {
        $response = $next($request, $response);
    } catch (Exception $e) {
        $response = $this->exceptionResponse->withStatus(500);
        $response->getBody()->write("exception caught with message: " . $e->getMessage());
    }
    return $response;
}
```

So that the body output is not some random unidentified string.

**Comment by cxj** [comment]
I'll provide 1 or more pull requests to make the above suggested changes, if such changes meet your general approval on concept.

**Comment by pmjones** [comment]
Please!

**Comment by cxj** [comment]
I think the 2 above PRs that were merged resolve most of this issue.

**Comment by pmjones** [comment]
Excellent. I'll close the issue as a result, but please reopen it (or open a new one) as needed. Thanks!
