### ISSUE TITLE
[QUESTION] How to handle multiple action

### ISSUE THREAD

**Issue by acidvertigo** [radarphp/Radar.Project#23]
Hello I'm triyng to follow the ADR design pattern with Radar but i cannot understand what is the better way to handle multiple actions.

For example for a blog app I can have one action that reads all blog post categories (ReadPostCategories action.php) and another action that reads the current blog post (ReadBlogPostAction.php). These two actions should read two indipendent domain services that will return their Payload and then return to the Responder class the data.

The question is what is the better way to route to the action as i think is not possible to give the same route for two different action, may I have to build a new action that includes previous two actions?

**Comment by pmjones** [comment]
It sounds like you have two different actions, not one action: one that shows all the categories, and one that shows a single post. (I think I'm missing something from your question.)

**Comment by acidvertigo** [comment]
Yes exactly, but these two actions have to be on the same page.

**Comment by pmjones** [comment]
Aha! So, those are not "actions" -- those are "pieces of the page." The "action" is whatever page the HTTP request is asking for.

It sounds like what you want in this case is to have your Action call a Service of some sort. (That Service is in the Domain.) The Service, for its part, makes all the other Domain calls, collects the results, and returns a Payload back to the Action. In this case, it sounds like the Payload will carry a result for the blog post itself, and a result for the categories.

So your Action only makes one call to the Domain; that is, to the Service. The Service can make as many calls as it wants, and returns just the one Payload.

Does that begin to help?

**Comment by acidvertigo** [comment]
Aha! ok now I understood better, I was giving too many responsability to the action instead. Thank you this clears all!
