### ISSUE TITLE
Question regarding composer.json

### ISSUE THREAD

**Issue by harikt** [radarphp/Radar.Project#8]
Hi Paul,

I don't have 5.6 to test this, but I have a doubt that the release `composer.json` values are wrong.

My belief is that when you keep `"minimum-stability": "dev"` flag on dev you are saying all the vendors should install the `dev` version. In this case when you tag a release alpha2 and composer create-project alpha will install a dev version of the adr and not alpha version.

The fix I feel is your composer.json should point to the `"radar/adr" : "~1.0@alpha"` and remove the minimum-stability flag dev from the project.

Change the `radar/adr` dependencies to make use of the alpha versions of `aura/router` and `aura/di` . As I have not tested but is the feeling I may be wrong also. But when I noticed I have a feeling of this.

**Comment by pmjones** [comment]
Test it out and let me know what happens.

**Comment by harikt** [comment]
@pmjones 

> I don't have 5.6 to test this .

In case you need, I did created a project and you can see the composer.json is exactly as same as  https://github.com/radarphp/Radar.Project/blob/1.0.0-alpha2/composer.json#L8 . 

That means it is same as creating a dev version.

**Comment by harikt** [comment]
So here you go 

``` php
$ composer create-project -s alpha something
$ cd something
```

after getting some information from https://twitter.com/yguedidi/status/603217885406826497

```
$ composer install --ignore-platform-reqs
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing josegonzalez/dotenv (0.7.1)
    Downloading: 100%         

  - Installing psr/http-message (dev-master 85d6369)
    Cloning 85d63699f0dbedb190bbd4b0d2b9dc707ea4c298

  - Installing psr/log (dev-master bf2c13d)
    Cloning bf2c13de4300e227d7b2fd08027673a79c519987

  - Installing aura/router (3.x-dev e7c3ad7)
    Cloning e7c3ad7c9b5d393de962a5526cd0b0a66b3fd1d5

  - Installing aura/payload-interface (3.x-dev 90ca6ff)
    Cloning 90ca6ff415760afceede472ed13a026cef0016a5

  - Installing aura/payload (3.x-dev f7800db)
    Cloning f7800db0da3f5b3e22fc57188f2c984bd6e66cf4

  - Installing container-interop/container-interop (1.1.0)
    Downloading: 100%         

  - Installing aura/di (3.x-dev 2d006dd)
    Cloning 2d006dd710c15f2ea65e800b542a49ebfd4c08a4

  - Installing radar/adr (dev-midwrap f02de7f)
    Cloning f02de7f8b2e26dff7e1ace6f60bef317688fb0f8

  - Installing zendframework/zend-diactoros (1.0.0)
    Downloading: 100%         

Writing lock file
Generating autoload files
```

You can see what I meant. You should consider removing the minimum-stability flags.

I don't know whether your mind at any point have thought I was trolling you, but I am not.

I have created PR's for the fix https://github.com/auraphp/Aura.Payload/pull/2 ( release needed ) , https://github.com/radarphp/Radar.Adr/pull/9 ( release needed ) , https://github.com/radarphp/Radar.Project/pull/9 ( release needed ) .

So that the alpha version use alpha not dev.

Thank you.

**Comment by harikt** [comment]
By the way couldn't send PR's on the last days where for I was having internet issues and limited access :-) .

**Comment by pmjones** [comment]
Thanks! Merged and released.
